### ISSUE TITLE
Reviewing before Registering

### ISSUE THREAD

**Issue by himanshugupta1009** [himanshugupta1009/PRM.jl#1]
@zsunberg please take a look at this package whenever you get a chance and suggest fixes if needed.
I can then move it to CU-ADCL and register it. Thanks!

**Comment by zsunberg** [comment]
I think that this looks good enough to register. It would be nice to have a simpler example.

If you want to improve the documentation and README, please have a look at the changes I made here: https://github.com/CU-ADCL/HybridAStar.jl/pull/5

A few more notes:
- Shouldn't `generate_prm` come before the other functions in the README?
- I think the name `node_values` could be improved. It sounds like it is the value function for the node or something. What about `node_state` or `node_location`?

**Comment by himanshugupta1009** [comment]
Made the recommended changes to the package. Thanks for the feedback. Registering it now.
