### ISSUE TITLE
How do you get a path

### ISSUE THREAD

**Issue by zsunberg** [himanshugupta1009/PRM.jl#4]
I see from the readme how to generate a graph, but how does one easily extract an optimal path from that graph?

**Comment by himanshugupta1009** [comment]
Added a blob at the end of the README to answer this. Please close the issue if you think the explanation is appropriate. Thanks!

**Comment by himanshugupta1009** [comment]
Added a blob at the end of the README to answer this. Let me know if you think the explanation is appropriate. Thanks!
